{"name": "test_logout", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\calvario31\\\\Documents\\\\Projects\\\\Selenium\\\\Python\\\\completeFramework\\\\tests\\\\resources\\\\logs\\\\appLog.log'", "trace": "request = <SubRequest 'manage_session' for <Function test_logout>>\n\n    @fixture(scope=\"session\", autouse=True)\n    def manage_session(request):\n        global browser, run_on_server, browser_version, os_version, operative_system\n        browser = request.config.getoption(\"--browser\")\n        browser_version = request.config.getoption(\"--browser\")\n        operative_system = request.config.getoption(\"--browser\")\n        os_version = request.config.getoption(\"--browser\")\n        run_on_server = os.environ.get(\"JOB_NAME\")\n>       log_manager.log = log_manager.get_logger()\n\nconftest.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nsrc\\utilities\\log_manager.py:45: in get_logger\n    file_handler = logging.FileHandler(\"./tests/resources/logs/appLog.log\", mode='w', delay=False)\n..\\..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1146: in __init__\n    StreamHandler.__init__(self, self._open())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <[AttributeError(\"'FileHandler' object has no attribute 'level'\") raised in repr()] FileHandler object at 0x221a3b84f70>\n\n    def _open(self):\n        \"\"\"\n        Open the current base file with the (original) mode and encoding.\n        Return the resulting stream.\n        \"\"\"\n>       return open(self.baseFilename, self.mode, encoding=self.encoding,\n                    errors=self.errors)\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\calvario31\\\\Documents\\\\Projects\\\\Selenium\\\\Python\\\\completeFramework\\\\tests\\\\resources\\\\logs\\\\appLog.log'\n\n..\\..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1175: FileNotFoundError"}, "start": 1631337561666, "stop": 1631337561666, "uuid": "bde9efb2-58c0-490c-a0ba-c1e31df1dad2", "historyId": "25752260b024d3c1ba9b84232379f3d2", "testCaseId": "802c00ee1e541ba84a16259ae54cfd41", "fullName": "tests.navigation.test_logout.TestLogout#test_logout", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests.navigation"}, {"name": "suite", "value": "test_logout"}, {"name": "subSuite", "value": "TestLogout"}, {"name": "host", "value": "hanna"}, {"name": "thread", "value": "10376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.navigation.test_logout"}]}